#!/bin/bash

BOLD_RED='\033[1;31m'
BOLD_PURPLE='\033[1;35m'
GREEN='\033[0;32m'
BOLD_YELLOW='\033[1;33m'
OFF='\033[0m'

CC="gcc"
CFLAGS="-Wall"

tput civis

# === Scanning === #
echo -e "${BOLD_PURPLE}Scanning dependencies of target executable${OFF}"
if [[ ! -f src/adc.c ]] || [[ ! -f src/base64.c ]] || [[ ! -f src/dmg2img.c ]]; then
	echo -e "${BOLD_RED}Error scanning src files! Check that all of them are there.. :/${OFF}"
	sleep 1.5; tput cnorm; exit 1
fi
sleep 2

# === Building === #
echo -e "[ 16%] ${GREEN}Building C object adc.o${OFF}"
# adc.o
$CC $CFLAGS -c src/adc.c
sleep 0.5
echo -e "[ 33%] ${GREEN}Building C object base64.o${OFF}"
# base64.o
$CC $CFLAGS -c src/base64.c
sleep 0.5
echo -e "[ 66%] ${GREEN}Building C object dmg2img.o${OFF}"
# dmg2img.o
$CC $CFLAGS -c src/dmg2img.c
sleep 1

# === Linking === #
echo -e "[ 99%] ${BOLD_YELLOW}Linking C executable dmg2img${OFF}"
$CC -s dmg2img.o base64.o adc.o -L. -lz -lbz2 -o dmg2img
sleep 0.5
echo -e "[100%] Built target dmg2img"

# === Cleaning === #
rm *.o

tput cnorm; exit 0
